// Generated by s11tnext-cli. Do not edit.
// compilerVersion: 0.1.2
// catalogDigest: sha256:42260ef2914c42043f455336244100cc0032721d97e32141cd0806a94883f360

import type { CatalogContract } from "s11tnext";
import { createCatalog } from "s11tnext";

export const expectedCatalogDigest = "sha256:42260ef2914c42043f455336244100cc0032721d97e32141cd0806a94883f360" as const;

export type PromptKey =
  | "contextCompiler.agenticRefine"
  | "contextCompiler.compose"
  | "contextCompiler.plan"
  | "contextDecision.answer"
  | "contextDecision.judge"
  | "contextDecision.repair"
  | "coverEvidence.applicabilityRefinement"
  | "coverEvidence.externalFetchSelection"
  | "coverEvidence.externalFinal"
  | "coverEvidence.externalSearchQuery"
  | "coverEvidence.mcpEvidence"
  | "coverEvidence.negative"
  | "coverEvidence.procedureRepair"
  | "coverEvidence.valueAssessment"
  | "episodeDistiller.generate"
  | "episodeDistiller.nearDuplicateReview"
  | "episodeDistiller.semanticChunk"
  | "findCandidate.codexEscalation"
  | "findCandidate.extract"
  | "findCandidate.vibeMemory"
  | "findCandidate.wiki"
  | "landscape.deadZoneMergeReview"
  | "provider.codex.finalResponse"
  | "shared.jsonOnly"
  | "sourceResearch.web";

export type PromptValueMap = {
  "contextCompiler.agenticRefine": {
    "changeTypes"?: string;
    "domains"?: string;
    "goal": string;
    "retrievalMode": string;
    "technologies"?: string;
  };
  "contextCompiler.compose": {
    "headingRule": string;
    "maxTokens": number;
    "styleRule": string;
  };
  "contextCompiler.plan": Record<string, never>;
  "contextDecision.answer": Record<string, never>;
  "contextDecision.judge": Record<string, never>;
  "contextDecision.repair": Record<string, never>;
  "coverEvidence.applicabilityRefinement": Record<string, never>;
  "coverEvidence.externalFetchSelection": {
    "maxFetchCount": number;
  };
  "coverEvidence.externalFinal": {
    "webEvidenceTokenBudget": number;
  };
  "coverEvidence.externalSearchQuery": Record<string, never>;
  "coverEvidence.mcpEvidence": {
    "toolNames": string;
  };
  "coverEvidence.negative": {
    "allowedIntentTags": string;
  };
  "coverEvidence.procedureRepair": Record<string, never>;
  "coverEvidence.valueAssessment": {
    "lowImportanceRejectThreshold": number;
  };
  "episodeDistiller.generate": Record<string, never>;
  "episodeDistiller.nearDuplicateReview": Record<string, never>;
  "episodeDistiller.semanticChunk": Record<string, never>;
  "findCandidate.codexEscalation": Record<string, never>;
  "findCandidate.extract": Record<string, never>;
  "findCandidate.vibeMemory": Record<string, never>;
  "findCandidate.wiki": Record<string, never>;
  "landscape.deadZoneMergeReview": Record<string, never>;
  "provider.codex.finalResponse": Record<string, never>;
  "shared.jsonOnly": Record<string, never>;
  "sourceResearch.web": Record<string, never>;
};

export type PromptOutputMap = {
  "contextCompiler.agenticRefine": "text";
  "contextCompiler.compose": "text";
  "contextCompiler.plan": "text";
  "contextDecision.answer": "text";
  "contextDecision.judge": "text";
  "contextDecision.repair": "text";
  "coverEvidence.applicabilityRefinement": "text";
  "coverEvidence.externalFetchSelection": "text";
  "coverEvidence.externalFinal": "text";
  "coverEvidence.externalSearchQuery": "text";
  "coverEvidence.mcpEvidence": "text";
  "coverEvidence.negative": "text";
  "coverEvidence.procedureRepair": "text";
  "coverEvidence.valueAssessment": "text";
  "episodeDistiller.generate": "text";
  "episodeDistiller.nearDuplicateReview": "text";
  "episodeDistiller.semanticChunk": "text";
  "findCandidate.codexEscalation": "text";
  "findCandidate.extract": "text";
  "findCandidate.vibeMemory": "text";
  "findCandidate.wiki": "text";
  "landscape.deadZoneMergeReview": "text";
  "provider.codex.finalResponse": "text";
  "shared.jsonOnly": "text";
  "sourceResearch.web": "text";
};

export type PromptMessageRoleMap = {
  "contextCompiler.agenticRefine": "system";
  "contextCompiler.compose": "system";
  "contextCompiler.plan": "system";
  "contextDecision.answer": "system";
  "contextDecision.judge": "system";
  "contextDecision.repair": "system";
  "coverEvidence.applicabilityRefinement": "system";
  "coverEvidence.externalFetchSelection": "system";
  "coverEvidence.externalFinal": "system";
  "coverEvidence.externalSearchQuery": "system";
  "coverEvidence.mcpEvidence": "system";
  "coverEvidence.negative": "system";
  "coverEvidence.procedureRepair": "system";
  "coverEvidence.valueAssessment": "system";
  "episodeDistiller.generate": "system";
  "episodeDistiller.nearDuplicateReview": "system";
  "episodeDistiller.semanticChunk": "system";
  "findCandidate.codexEscalation": "system";
  "findCandidate.extract": "system";
  "findCandidate.vibeMemory": "system";
  "findCandidate.wiki": "system";
  "landscape.deadZoneMergeReview": "system";
  "provider.codex.finalResponse": "system";
  "shared.jsonOnly": "system";
  "sourceResearch.web": "system";
};

/** @deprecated Use PromptKey. */
export type SystemContextKey = PromptKey;
/** @deprecated Use PromptValueMap. */
export type SystemContextValueMap = PromptValueMap;
/** @deprecated Use PromptOutputMap. */
export type SystemContextOutputMap = PromptOutputMap;

export type AppCatalogContract = CatalogContract<
  PromptKey,
  PromptValueMap,
  PromptOutputMap,
  PromptMessageRoleMap
>;

export function createAppCatalog(artifact: unknown) {
  return createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });
}
