// Generated by s11tnext-cli. Do not edit.
// compilerVersion: 0.1.0
// catalogDigest: sha256:f979597403ef700c24fb015e4fb269a98eeae4d3982d906578b5984d0bf56ebc

import type { CatalogContract } from "s11tnext";
import { createCatalog } from "s11tnext";

export const expectedCatalogDigest = "sha256:f979597403ef700c24fb015e4fb269a98eeae4d3982d906578b5984d0bf56ebc" as const;

export type SystemContextKey =
	| "contextCompiler.agenticRefine"
	| "contextCompiler.compose"
	| "contextCompiler.plan"
	| "contextDecision.answer"
	| "contextDecision.judge"
	| "contextDecision.repair"
	| "coverEvidence.applicabilityRefinement"
	| "coverEvidence.externalFetchSelection"
	| "coverEvidence.externalFinal"
	| "coverEvidence.externalSearchQuery"
	| "coverEvidence.mcpEvidence"
	| "coverEvidence.negative"
	| "coverEvidence.procedureRepair"
	| "coverEvidence.valueAssessment"
	| "episodeDistiller.generate"
	| "episodeDistiller.nearDuplicateReview"
	| "episodeDistiller.semanticChunk"
	| "findCandidate.codexEscalation"
	| "findCandidate.extract"
	| "findCandidate.vibeMemory"
	| "findCandidate.wiki"
	| "landscape.deadZoneMergeReview"
	| "provider.codex.finalResponse"
	| "shared.jsonOnly"
	| "sourceResearch.web";

export type SystemContextValueMap = {
	"contextCompiler.agenticRefine": {
		"changeTypes": string;
		"domains": string;
		"goal": string;
		"retrievalMode": string;
		"technologies": string;
	};
	"contextCompiler.compose": {
		"headingRule": string;
		"maxTokens": number;
		"styleRule": string;
	};
	"contextCompiler.plan": Record<string, never>;
	"contextDecision.answer": Record<string, never>;
	"contextDecision.judge": Record<string, never>;
	"contextDecision.repair": Record<string, never>;
	"coverEvidence.applicabilityRefinement": Record<string, never>;
	"coverEvidence.externalFetchSelection": {
		"maxFetchCount": number;
	};
	"coverEvidence.externalFinal": {
		"webEvidenceTokenBudget": number;
	};
	"coverEvidence.externalSearchQuery": Record<string, never>;
	"coverEvidence.mcpEvidence": {
		"toolNames": string;
	};
	"coverEvidence.negative": {
		"allowedIntentTags": string;
	};
	"coverEvidence.procedureRepair": Record<string, never>;
	"coverEvidence.valueAssessment": {
		"lowImportanceRejectThreshold": number;
	};
	"episodeDistiller.generate": Record<string, never>;
	"episodeDistiller.nearDuplicateReview": Record<string, never>;
	"episodeDistiller.semanticChunk": Record<string, never>;
	"findCandidate.codexEscalation": Record<string, never>;
	"findCandidate.extract": Record<string, never>;
	"findCandidate.vibeMemory": Record<string, never>;
	"findCandidate.wiki": Record<string, never>;
	"landscape.deadZoneMergeReview": Record<string, never>;
	"provider.codex.finalResponse": Record<string, never>;
	"shared.jsonOnly": Record<string, never>;
	"sourceResearch.web": Record<string, never>;
};

export type SystemContextOutputMap = {
	"contextCompiler.agenticRefine": "text";
	"contextCompiler.compose": "text";
	"contextCompiler.plan": "text";
	"contextDecision.answer": "text";
	"contextDecision.judge": "text";
	"contextDecision.repair": "text";
	"coverEvidence.applicabilityRefinement": "text";
	"coverEvidence.externalFetchSelection": "text";
	"coverEvidence.externalFinal": "text";
	"coverEvidence.externalSearchQuery": "text";
	"coverEvidence.mcpEvidence": "text";
	"coverEvidence.negative": "text";
	"coverEvidence.procedureRepair": "text";
	"coverEvidence.valueAssessment": "text";
	"episodeDistiller.generate": "text";
	"episodeDistiller.nearDuplicateReview": "text";
	"episodeDistiller.semanticChunk": "text";
	"findCandidate.codexEscalation": "text";
	"findCandidate.extract": "text";
	"findCandidate.vibeMemory": "text";
	"findCandidate.wiki": "text";
	"landscape.deadZoneMergeReview": "text";
	"provider.codex.finalResponse": "text";
	"shared.jsonOnly": "text";
	"sourceResearch.web": "text";
};

export type AppCatalogContract = CatalogContract<
	SystemContextKey,
	SystemContextValueMap,
	SystemContextOutputMap
>;

export function createAppCatalog(artifact: unknown) {
	return createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });
}
