// Generated by s11tnext-cli. Do not edit.
// compilerVersion: 0.1.2
// catalogDigest: sha256:39f9fcadb942c28f458ae61f7e6822ec6f23585c24792b2c0f8401acde5224f0

import type { CatalogContract } from "s11tnext";
import { createCatalog } from "s11tnext";

export const expectedCatalogDigest = "sha256:39f9fcadb942c28f458ae61f7e6822ec6f23585c24792b2c0f8401acde5224f0" as const;

export type PromptKey =
  | "contextCompiler.selectEvidence";

export type PromptValueMap = {
  "contextCompiler.selectEvidence": Record<string, never>;
};

export type PromptOutputMap = {
  "contextCompiler.selectEvidence": "text";
};

export type PromptMessageRoleMap = {
  "contextCompiler.selectEvidence": "system";
};

/** @deprecated Use PromptKey. */
export type SystemContextKey = PromptKey;
/** @deprecated Use PromptValueMap. */
export type SystemContextValueMap = PromptValueMap;
/** @deprecated Use PromptOutputMap. */
export type SystemContextOutputMap = PromptOutputMap;

export type AppCatalogContract = CatalogContract<
  PromptKey,
  PromptValueMap,
  PromptOutputMap,
  PromptMessageRoleMap
>;

export function createAppCatalog(artifact: unknown) {
  return createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });
}
